// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq7cSjLXKITxiup4XZg-2YJnEBF0XnCMQ',
    appId: '1:585681045503:web:aad51cd5f1b77a1a6209ca',
    messagingSenderId: '585681045503',
    projectId: 'moshaaaaaa',
    authDomain: 'moshaaaaaa.firebaseapp.com',
    storageBucket: 'moshaaaaaa.firebasestorage.app',
    measurementId: 'G-5D0GCPERRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvcWKAUt9CaDG7Z2gEW91lP-U0ImuiNVk',
    appId: '1:585681045503:android:49a22bd359166d176209ca',
    messagingSenderId: '585681045503',
    projectId: 'moshaaaaaa',
    storageBucket: 'moshaaaaaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4kRKFwZOFSuZ3JLWqV29I3g4_WCasbwU',
    appId: '1:585681045503:ios:8ee9163ac464a4676209ca',
    messagingSenderId: '585681045503',
    projectId: 'moshaaaaaa',
    storageBucket: 'moshaaaaaa.firebasestorage.app',
    iosBundleId: 'com.mosquit.moshaaaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4kRKFwZOFSuZ3JLWqV29I3g4_WCasbwU',
    appId: '1:585681045503:ios:8ee9163ac464a4676209ca',
    messagingSenderId: '585681045503',
    projectId: 'moshaaaaaa',
    storageBucket: 'moshaaaaaa.firebasestorage.app',
    iosBundleId: 'com.mosquit.moshaaaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq7cSjLXKITxiup4XZg-2YJnEBF0XnCMQ',
    appId: '1:585681045503:web:d2c9eec3b8dc25716209ca',
    messagingSenderId: '585681045503',
    projectId: 'moshaaaaaa',
    authDomain: 'moshaaaaaa.firebaseapp.com',
    storageBucket: 'moshaaaaaa.firebasestorage.app',
    measurementId: 'G-5JFC59BGPV',
  );
}
